var HTML=
{
	'5':
	{
		'ACTUAL':
		[
			'ARTICLE','ASIDE','AUDIO','BB','CANVAS','COMMAND','DATAGRID','DATALIST','DETAILS','DIALOG','EMBED','FIGURE','FOOTER','HEADER','HGROUP','MARK','METER','NAV','OUTPUT','PROGRESS','RUBY','RP','RT','SECTION','SOURCE','TIME','VIDEO'
		]
		,
		'BEFORE':
		[
			'A','ABBR','ADDRESS','AREA','B','BASE','BDO','BLOCKQUOTE','BODY','BR','BUTTON','CAPTION','CITE','CODE','COL','COLGROUP','DD','DEL','DIV','DFN','DL','DT','EM','FIELDSET','FORM','H1','H2','H3','H4','H5','H6','HEAD','HR','HTML','I','IFRAME','IMG','INPUT','INS','KBD','LABEL','LEGEND','LI','LINK','MAP','MENU','META','NOSCRIPT','OBJECT','OL','OPTGROUP','OPTION','P','PARAM','PRE','Q','SAMP','SCRIPT','SELECT','SMALL','SPAN','STRONG','STYLE','SUB','SUP','TABLE','TBODY','TD','TEXTAREA','TFOOT','TH','THEAD','TITLE','TR','UL','VAR'
		]
		,
		'BEYOND':
		[
			'ACRONYM','APPLET','BASEFONT','BIG','CENTER','DIR','FONT','FRAME','FRAMESET','ISINDEX','NOFRAMES','S','STRIKE','TT','U','XMP'
		]
	}
	,
	'TAGS':
	{
		'ARTICLE':
		function(v)
		{
			
		}
		,
		'ASIDE':
		function(v)
		{
			
		}
		,
		'AUDIO':
		function(v)
		{
			
		}
		,
		'BB':
		function(v)
		{
			
		}
		,
		'CANVAS':
		function(v)
		{
			
		}
		,
		'COMMAND':
		function(v)
		{
			
		}
		,
		'DATAGRID':
		function(v)
		{
			
		}
		,
		'DATALIST':
		function(v)
		{
			
		}
		,
		'DETAILS':
		function(v)
		{
			
		}
		,
		'DIALOG':
		function(v)
		{
			
		}
		,
		'EMBED':
		function(v)
		{
			
		}
		,
		'FIGURE':
		function(v)
		{
			
		}
		,
		'FOOTER':
		function(v)
		{
			
		}
		,
		'HEADER':
		function(v)
		{
			
		}
		,
		'HGROUP':
		function(v)
		{
			
		}
		,
		'MARK':
		function(v)
		{
			
		}
		,
		'METER':
		function(v)
		{
			
		}
		,
		'NAV':
		function(v)
		{
			
		}
		,
		'OUTPUT':
		function(v)
		{
			
		}
		,
		'PROGRESS':
		function(v)
		{
			
		}
		,
		'RUBY':
		function(v)
		{
			
		}
		,
		'RP':
		function(v)
		{
			
		}
		,
		'RT':
		function(v)
		{
			
		}
		,
		'SECTION':
		function(v)
		{
			
		}
		,
		'SOURCE':
		function(v)
		{
			
		}
		,
		'TIME':
		function(v)
		{
			
		}
		,
		'VIDEO':
		function(v)
		{
			
		}
		,
		'A':
		function(v)
		{
			
		}
		,
		'ABBR':
		function(v)
		{
			
		}
		,
		'ADDRESS':
		function(v)
		{
			
		}
		,
		'AREA':
		function(v)
		{
			
		}
		,
		'B':
		function(v)
		{
			
		}
		,
		'BASE':
		function(v)
		{
			
		}
		,
		'BDO':
		function(v)
		{
			
		}
		,
		'BLOCKQUOTE':
		function(v)
		{
			
		}
		,
		'BODY':
		function(v)
		{
			
		}
		,
		'BR':
		function(v)
		{
			
		}
		,
		'BUTTON':
		function(v)
		{
			
		}
		,
		'CAPTION':
		function(v)
		{
			
		}
		,
		'CITE':
		function(v)
		{
			
		}
		,
		'CODE':
		function(v)
		{
			
		}
		,
		'COL':
		function(v)
		{
			
		}
		,
		'COLGROUP':
		function(v)
		{
			
		}
		,
		'DD':
		function(v)
		{
			
		}
		,
		'DEL':
		function(v)
		{
			
		}
		,
		'DIV':
		function(v)
		{
			
		}
		,
		'DFN':
		function(v)
		{
			
		}
		,
		'DL':
		function(v)
		{
			
		}
		,
		'DT':
		function(v)
		{
			
		}
		,
		'EM':
		function(v)
		{
			
		}
		,
		'FIELDSET':
		function(v)
		{
			
		}
		,
		'FORM':
		function(v)
		{
			
		}
		,
		'H1':
		function(v)
		{
			
		}
		,
		'H2':
		function(v)
		{
			
		}
		,
		'H3':
		function(v)
		{
			
		}
		,
		'H4':
		function(v)
		{
			
		}
		,
		'H5':
		function(v)
		{
			
		}
		,
		'H6':
		function(v)
		{
			
		}
		,
		'HEAD':
		function(v)
		{
			
		}
		,
		'HR':
		function(v)
		{
			
		}
		,
		'HTML':
		function(v)
		{
			
		}
		,
		'I':
		function(v)
		{
			
		}
		,
		'IFRAME':
		function(v)
		{
			
		}
		,
		'IMG':
		function(v)
		{
			
		}
		,
		'INPUT':
		function(v)
		{
			
		}
		,
		'INS':
		function(v)
		{
			
		}
		,
		'KBD':
		function(v)
		{
			
		}
		,
		'LABEL':
		function(v)
		{
			
		}
		,
		'LEGEND':
		function(v)
		{
			
		}
		,
		'LI':
		function(v)
		{
			
		}
		,
		'LINK':
		function(v)
		{
			
		}
		,
		'MAP':
		function(v)
		{
			
		}
		,
		'MENU':
		function(v)
		{
			
		}
		,
		'META':
		function(v)
		{
			
		}
		,
		'NOSCRIPT':
		function(v)
		{
			
		}
		,
		'OBJECT':
		function(v)
		{
			
		}
		,
		'OL':
		function(v)
		{
			
		}
		,
		'OPTGROUP':
		function(v)
		{
			
		}
		,
		'OPTION':
		function(v)
		{
			
		}
		,
		'P':
		function(v)
		{
			
		}
		,
		'PARAM':
		function(v)
		{
			
		}
		,
		'PRE':
		function(v)
		{
			
		}
		,
		'Q':
		function(v)
		{
			
		}
		,
		'SAMP':
		function(v)
		{
			
		}
		,
		'SCRIPT':
		function(v)
		{
			
		}
		,
		'SELECT':
		function(v)
		{
			
		}
		,
		'SMALL':
		function(v)
		{
			
		}
		,
		'SPAN':
		function(v)
		{
			
		}
		,
		'STRONG':
		function(v)
		{
			
		}
		,
		'STYLE':
		function(v)
		{
			
		}
		,
		'SUB':
		function(v)
		{
			
		}
		,
		'SUP':
		function(v)
		{
			
		}
		,
		'TABLE':
		function(v)
		{
			
		}
		,
		'TBODY':
		function(v)
		{
			
		}
		,
		'TD':
		function(v)
		{
			
		}
		,
		'TEXTAREA':
		function(v)
		{
			
		}
		,
		'TFOOT':
		function(v)
		{
			
		}
		,
		'TH':
		function(v)
		{
			
		}
		,
		'THEAD':
		function(v)
		{
			
		}
		,
		'TITLE':
		function(v)
		{
			
		}
		,
		'TR':
		function(v)
		{
			
		}
		,
		'UL':
		function(v)
		{
			
		}
		,
		'VAR':
		function(v)
		{
			
		}
	}
}
